# For testing and development.

---
services:
  operations:
    image: geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest
    hostname: server.company.com
    cgroup: host
    cgroup_parent: docker.slice
    privileged: true
    working_dir: /app
    volumes:
      - ./:/app
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      
      # We want it to work from local repo only.
      # - ./ansible:/etc/ansible
