# For testing and development.

---
services:
  operations:
    image: geerlingguy/docker-${DISTRO:-rockylinux10}-ansible:latest
    hostname: ${DOCKER_HOSTNAME:-server.mydomain.com}
    cgroup: host
    cgroup_parent: docker.slice
    privileged: true
    working_dir: /app
    volumes:
      - ./:/app
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      - OPERATIONS_PLATFORM=yes
    env_file:
      - .env
    build: ./
