#
# Example host inventory file.
#
# This is a standard Ansible host inventory file.
# It is not strictly necessary.
#
# You can use inventory.yml or this.
#
# It stores variables for the host with the same name as the file.
# You could use this for secrets storage if you are comfortable putting it right on the server.
# But really, you should save your secrets in GitHub secrets and pass to ansible-playbook in your GitHub workflows.
#
