#!/bin/bash

set -e
# Usage
#
# REPO owner/repo
# RUN_ID the run to check.
# ATTEMPT The run attempt.
# JOB_NAME If supplied, only check this job.
# EXCLUDE_JOB_NAME  if supplied, exclude the job with this name.
#   In order to use this script (jobs-done) in a job, you have to exclude itself or it will run forever.
#

REPO=${REPO:-$(gh repo view --json 'nameWithOwner' --jq '.nameWithOwner')}
echo $REPO

if [[ -n $JOB_NAME ]]; then
  JQ=".jobs[] | select(.name = \"$JOB_NAME\") | select(.status != \"completed\") | .status"

elif [[ -n $EXCLUDE_JOB_NAME ]]; then
  JQ=".jobs[] | select(.name != \"$EXCLUDE_JOB_NAME\") | select(.status != \"completed\") | .status"

else
  JQ=".jobs[] | select(.status != \"completed\") | .status"

fi

JOBS=$(gh api /repos/$REPO/actions/runs/$RUN_ID/attempts/$ATTEMPT/jobs \
  | jq -e "$JQ")

if [[ -n $JOBS ]]; then
  echo "Jobs are still running."
  exit 1
else
  echo "Jobs done!"
fi